services:
  python:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: back
    ports:
      - "49515:5000"
    #restart: always
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /app

