# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\rsearchscholar\"%\n\x14SearchScholarRequest\x12\r\n\x05query\x18\x01 \x01(\t\"E\n\x15SearchScholarResponse\x12,\n\x07results\x18\x01 \x03(\x0b\x32\x1b.searchscholar.SearchResult\"\xc5\x01\n\x0cSearchResult\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x12\n\nconference\x18\x04 \x01(\t\x12\r\n\x05pages\x18\x05 \x01(\x05\x12\x0c\n\x04\x64\x61te\x18\x06 \x01(\t\x12\x10\n\x08\x61\x62stract\x18\x07 \x01(\t\x12\x10\n\x08\x63ite_num\x18\x08 \x01(\x05\x12\x11\n\tsubmitted\x18\t \x01(\x08\x12\x13\n\x0brelevant_no\x18\n \x01(\x05\x12\x0c\n\x04tier\x18\x0b \x01(\x05\x32\x64\n\rSearchScholar\x12S\n\x06Search\x12#.searchscholar.SearchScholarRequest\x1a$.searchscholar.SearchScholarResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHSCHOLARREQUEST']._serialized_start=32
  _globals['_SEARCHSCHOLARREQUEST']._serialized_end=69
  _globals['_SEARCHSCHOLARRESPONSE']._serialized_start=71
  _globals['_SEARCHSCHOLARRESPONSE']._serialized_end=140
  _globals['_SEARCHRESULT']._serialized_start=143
  _globals['_SEARCHRESULT']._serialized_end=340
  _globals['_SEARCHSCHOLAR']._serialized_start=342
  _globals['_SEARCHSCHOLAR']._serialized_end=442
# @@protoc_insertion_point(module_scope)
